# Generated by Django 3.0.3 on 2021-09-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pinkproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('color_r', models.IntegerField(default=255)),
                ('color_g', models.IntegerField(default=255)),
                ('color_b', models.IntegerField(default=255)),
            ],
        ),
        migrations.CreateModel(
            name='SOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som_name', models.CharField(max_length=200)),
                ('som_width', models.IntegerField()),
                ('som_height', models.IntegerField()),
                ('som_depth', models.IntegerField()),
                ('layout', models.CharField(max_length=200)),
                ('number_of_neurons', models.IntegerField()),
                ('mapping_generated', models.BooleanField(default=False)),
                ('som_file', models.FileField(upload_to='projects')),
                ('mapping_file', models.FileField(null=True, upload_to='projects')),
                ('heatmap', models.ImageField(default=None, null=True, upload_to='')),
                ('histogram', models.ImageField(default=None, null=True, upload_to='')),
                ('proto_grid', models.ImageField(default=None, null=True, upload_to='')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkproject.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('number_of_fits', models.IntegerField()),
                ('image', models.CharField(default='', max_length=200)),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='som.Label')),
                ('som', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='som.SOM')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='som',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='som.SOM'),
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('image', models.CharField(default='', max_length=200)),
                ('closest_proto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='som.Prototype')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='som.Label')),
                ('som', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='som.SOM')),
            ],
            options={
                'unique_together': {('som', 'index')},
            },
        ),
    ]
