# Generated by Django 2.2.3 on 2019-09-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='som',
            name='layout',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='som',
            name='som_depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='som',
            name='som_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='som',
            name='som_width',
            field=models.IntegerField(),
        ),
    ]
