# Generated by Django 2.2.3 on 2019-09-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0002_auto_20190909_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='som',
            name='heatmap_path',
            field=models.FileField(default='heatmap.png', upload_to='cutouts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='som',
            name='histogram_path',
            field=models.FileField(default='histogram.png', upload_to='cutouts'),
            preserve_default=False,
        ),
    ]
