# Generated by Django 2.2.3 on 2019-09-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0003_auto_20190909_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='som',
            name='heatmap_path',
        ),
        migrations.RemoveField(
            model_name='som',
            name='histogram_path',
        ),
        migrations.AddField(
            model_name='som',
            name='heatmap',
            field=models.ImageField(default='EFIGI/protos.png', upload_to='cutouts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='som',
            name='histogram',
            field=models.ImageField(default='EFIGI/histogram.png', upload_to='cutouts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='som',
            name='proto_map',
            field=models.ImageField(default='prototypes/EFIGI/protos.png', upload_to='cutouts'),
            preserve_default=False,
        ),
    ]
