# Generated by Django 2.2.3 on 2019-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0004_auto_20190910_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='som',
            name='histogram',
            field=models.ImageField(upload_to='prototypes'),
        ),
    ]
