# Generated by Django 2.2.3 on 2019-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0005_auto_20190910_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='label',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='somcutout',
            name='label',
            field=models.CharField(default='', max_length=200),
        ),
    ]
