# Generated by Django 2.2.3 on 2019-09-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0006_auto_20190917_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlier',
            name='label',
            field=models.CharField(default='', max_length=200),
        ),
    ]
