# Generated by Django 3.0.3 on 2021-09-02 14:50

from django.db import migrations, models
import django.db.models.deletion
import pinkproject.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('thumbnail', models.ImageField(default=None, null=True, upload_to=pinkproject.models.upload_to_project_folder)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=200)),
                ('description', models.TextField(default='No description...', max_length=2000)),
                ('length', models.IntegerField()),
                ('data_path', models.FileField(upload_to='projects')),
                ('csv_path', models.FileField(default=None, upload_to='projects')),
                ('obj_identifier_key', models.CharField(default='ObjName', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkproject.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='data')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkproject.Project')),
            ],
        ),
    ]
