# Generated by Django 2.2.3 on 2019-09-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('current_project', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='data')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkproject.Project')),
            ],
        ),
    ]
